In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv('xAPI-Edu-Data.csv')
data.head()

,gender,NationalITy,PlaceofBirth,StageID,GradeID,SectionID,Topic,Semester,Relation,raisedhands,VisITedResources,AnnouncementsView,Discussion,ParentAnsweringSurvey,ParentschoolSatisfaction,StudentAbsenceDays,Class
0,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,15,16,2,20,Yes,Good,Under-7,M
1,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,20,20,3,25,Yes,Good,Under-7,M
2,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,10,7,0,30,No,Bad,Above-7,L
3,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,30,25,5,35,No,Bad,Above-7,L
4,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,40,50,12,50,No,Bad,Above-7,M

In [3]:
data['gender'].replace('M', 0,inplace=True)
data['gender'].replace('F', 1,inplace=True)

# Or we can use get_dummies to convert categorical values and concatenate them later
nat = pd.get_dummies(data['NationalITy'])
sid = pd.get_dummies(data['StageID'])
gid = pd.get_dummies(data['GradeID'])
secid = pd.get_dummies(data['SectionID'])
topic = pd.get_dummies(data['Topic'])
semester = pd.get_dummies(data['Semester'])
rel = pd.get_dummies(data['Relation'])
pas = pd.get_dummies(data['ParentAnsweringSurvey'])
pss = pd.get_dummies(data['ParentschoolSatisfaction'])
sab = pd.get_dummies(data['StudentAbsenceDays'])

In [4]:
# Concatenating the variables we created above 
df = pd.concat([data,nat,sid,gid,secid,topic,semester,rel,pas,pss,sab],axis=1)

In [5]:
df.drop(['NationalITy','PlaceofBirth','PlaceofBirth','StageID','GradeID','SectionID','Topic','Semester',
              'Relation','ParentAnsweringSurvey','ParentschoolSatisfaction','StudentAbsenceDays'],axis=1,inplace=True)

In [6]:
df.columns

Index(['gender', 'raisedhands', 'VisITedResources', 'AnnouncementsView',
       'Discussion', 'Class', 'Egypt', 'Iran', 'Iraq', 'Jordan', 'KW', 'Lybia',
       'Morocco', 'Palestine', 'SaudiArabia', 'Syria', 'Tunis', 'USA',
       'lebanon', 'venzuela', 'HighSchool', 'MiddleSchool', 'lowerlevel',
       'G-02', 'G-04', 'G-05', 'G-06', 'G-07', 'G-08', 'G-09', 'G-10', 'G-11',
       'G-12', 'A', 'B', 'C', 'Arabic', 'Biology', 'Chemistry', 'English',
       'French', 'Geology', 'History', 'IT', 'Math', 'Quran', 'Science',
       'Spanish', 'F', 'S', 'Father', 'Mum', 'No', 'Yes', 'Bad', 'Good',
       'Above-7', 'Under-7'],
      dtype='object')

In [7]:
Label = df['Class'] # Class is the value we want to predict

Features = df[['gender', 'raisedhands', 'VisITedResources', 'AnnouncementsView',
       'Discussion','Father', 'Mum', 'No', 'Yes', 'Bad', 'Good',
       'Above-7', 'Under-7']]

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(Features)
scaled = scaler.transform(Features)

In [19]:
pd.DataFrame(scaled,columns=Features.columns)

,gender,raisedhands,VisITedResources,AnnouncementsView,Discussion,Father,Mum,No,Yes,Bad,Good,Above-7,Under-7
0,-0.757476,-1.033429,-1.174075,-1.351167,-0.843326,0.834334,-0.834334,-0.881917,0.881917,-0.802394,0.802394,-0.812957,0.812957
1,-0.757476,-0.870813,-1.053029,-1.313549,-0.662225,0.834334,-0.834334,-0.881917,0.881917,-0.802394,0.802394,-0.812957,0.812957
2,-0.757476,-1.196046,-1.446426,-1.426401,-0.481125,0.834334,-0.834334,1.133893,-1.133893,1.246271,-1.246271,1.230077,-1.230077
3,-0.757476,-0.545579,-0.901723,-1.238315,-0.300024,0.834334,-0.834334,1.133893,-1.133893,1.246271,-1.246271,1.230077,-1.230077
4,-0.757476,-0.220346,-0.145191,-0.974994,0.243279,0.834334,-0.834334,1.133893,-1.133893,1.246271,-1.246271,1.230077,-1.230077
...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,1.320173,-1.358663,-1.537210,-1.238315,-1.277968,0.834334,-0.834334,1.133893,-1.133893,1.246271,-1.246271,1.230077,-1.230077
476,1.320173,0.104888,0.671863,-0.899759,-0.553565,0.834334,-0.834334,1.133893,-1.133893,1.246271,-1.246271,-0.812957,0.812957
477,1.320173,0.267505,0.581080,-0.485969,-0.517345,0.834334,-0.834334,1.133893,-1.133893,1.246271,-1.246271,-0.812957,0.812957
478,1.320173,-0.545579,-1.143813,-0.899759,0.496820,0.834334,-0.834334,1.133893,-1.133893,1.246271,-1.246271,1.230077,-1.230077
479,1.320173,-0.382962,-1.234597,-0.561203,0.677921,0.834334,-0.834334,1.133893,-1.133893,1.246271,-1.246271,1.230077,-1.230077

In [10]:
from sklearn.model_selection import train_test_split
X = scaled
y = Label
# split the data to 20% test,80% train with random state=42
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [14]:
rfc = RandomForestClassifier(n_estimators=80,max_features='auto', max_depth=9,min_samples_leaf=1,
                             min_samples_split=2,bootstrap=True, random_state = 42)
rfc.fit(X_train,y_train)
rfcpred = rfc.predict(X_test)
print(classification_report(y_test,rfcpred))

              precision    recall  f1-score   support

           H       0.86      0.82      0.84        22
           L       0.89      0.96      0.93        26
           M       0.89      0.88      0.88        48

    accuracy                           0.89        96
   macro avg       0.88      0.88      0.88        96
weighted avg       0.89      0.89      0.88        96

/Users/ujjwalkohli/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:427: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(